version: '3.8'

services:
  api:
    # image: planner-backend:latest
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    # env_file:
    #   - ./backend/.env

    #   web:
    #     image: planner/frontend:latest
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
