version: '3.8'

networks:
  caddy:
services:
  web:
    build: ./frontend
    container_name: planner-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - caddy
    depends_on:
      - api
    env_file:
      - ./frontend/.env
  api:
    build: ./backend
    container_name: planner-api
    ports:
      - "8000:8000"
    networks:
      - caddy
    depends_on:
      - db
    volumes:
      - ./siding-mock-data:/code/siding-mock-data
    env_file:
      - ./backend/.env
  db:
    image: postgres:latest
    container_name: planner-db
    ports:
      - "5432:5432"
    networks:
      - caddy
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./database/.env
volumes:
  postgres-data:
