---
- name: Deploy Planner
  hosts: all
  become: true

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    - name: Add Docker repository
      ansible.builtin.dnf_repository:
        name: docker
        description: Docker Repository
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        gpgcheck: true

    - name: Install Docker
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Install Docker Compose
      dnf:
        name: docker-compose-plugin
        state: present

    - name: Create Docker volume for Caddy
      community.docker.docker_volume:
        name: caddy_data
        state: present

    - name: Build and run Docker containers
      # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
      community.docker.docker_compose:
        project_src: /opt/planner
        state: present
        build: true
        recreate: always
        remove_orphans: true
        restarted: true
        pull: true
        timeout: 300
        services:
          - planner
